
import { LanguageColor } from './types';
import {
  SiJavascript, SiTypescript, SiReact, SiVuedotjs, SiAngular, SiNodedotjs, SiNextdotjs,
  SiNuxtdotjs, SiSvelte, SiSolid, SiHtml5, SiCss3, SiSass, SiTailwindcss,
  SiPython, SiDjango, SiFastapi, SiSharp, SiDotnet, SiPhp, SiLaravel,
  SiGo, SiRust, SiSwift, SiKotlin, SiFlutter, SiDart, SiPostgresql,
  SiMysql, SiMongodb, SiRedis, SiFirebase, SiSupabase, SiDocker,
  SiKubernetes, SiAmazonwebservices, SiGooglecloud, SiJest, SiCypress,
  SiSolidity, SiEthereum, SiTensorflow, SiPytorch, FaJava, FaCode
} from './icons';

export const LANGUAGE_COLORS: Record<string, LanguageColor> = {
  // Frontend - JavaScript Ecosystem
  'javascript': {
    name: 'javascript',
    displayName: 'JavaScript',
    color: '#F7DF1E',
    bgColor: 'bg-yellow-400',
    textColor: 'text-yellow-900',
    gradient: 'from-yellow-400 to-yellow-500',
    icon: SiJavascript,
    category: 'frontend',
    difficulty: 2,
    trending: true,
    popularity: 10,
    description: 'Linguagem de programação versátil para web',
    keywords: ['js', 'javascript', 'ecmascript', 'es6', 'es2015', 'node', 'browser', 'web']
  },
  'typescript': {
    name: 'typescript',
    displayName: 'TypeScript',
    color: '#3178C6',
    bgColor: 'bg-blue-500',
    textColor: 'text-blue-100',
    gradient: 'from-blue-500 to-blue-600',
    icon: SiTypescript,
    category: 'frontend',
    difficulty: 3,
    trending: true,
    popularity: 9,
    description: 'JavaScript com tipagem estática',
    keywords: ['ts', 'typescript', 'types', 'static typing', 'microsoft']
  },
  'react': {
    name: 'react',
    displayName: 'React',
    color: '#61DAFB',
    bgColor: 'bg-cyan-400',
    textColor: 'text-cyan-900',
    gradient: 'from-cyan-400 to-cyan-500',
    icon: SiReact,
    category: 'frontend',
    difficulty: 3,
    trending: true,
    popularity: 10,
    description: 'Biblioteca para interfaces de usuário',
    keywords: ['react', 'reactjs', 'jsx', 'components', 'hooks', 'facebook', 'meta']
  },
  'nextjs': {
    name: 'nextjs',
    displayName: 'Next.js',
    color: '#000000',
    bgColor: 'bg-black',
    textColor: 'text-white',
    gradient: 'from-black to-gray-800',
    icon: SiNextdotjs,
    category: 'frontend',
    difficulty: 3,
    trending: true,
    popularity: 9,
    description: 'Framework React para produção',
    keywords: ['nextjs', 'next', 'ssr', 'static generation', 'vercel', 'fullstack']
  },
  'vue': {
    name: 'vue',
    displayName: 'Vue.js',
    color: '#4FC08D',
    bgColor: 'bg-green-500',
    textColor: 'text-green-100',
    gradient: 'from-green-500 to-green-600',
    icon: SiVuedotjs,
    category: 'frontend',
    difficulty: 2,
    trending: true,
    popularity: 8,
    description: 'Framework progressivo para interfaces',
    keywords: ['vue', 'vuejs', 'vue.js', 'composition api', 'evan you']
  },
  'angular': {
    name: 'angular',
    displayName: 'Angular',
    color: '#DD0031',
    bgColor: 'bg-red-600',
    textColor: 'text-red-100',
    gradient: 'from-red-600 to-red-700',
    icon: SiAngular,
    category: 'frontend',
    difficulty: 4,
    trending: true,
    popularity: 7,
    description: 'Framework TypeScript para aplicações web',
    keywords: ['angular', 'ng', 'typescript', 'google', 'spa', 'cli']
  },
  'node': {
    name: 'node',
    displayName: 'Node.js',
    color: '#339933',
    bgColor: 'bg-green-600',
    textColor: 'text-green-100',
    gradient: 'from-green-600 to-green-700',
    icon: SiNodedotjs,
    category: 'backend',
    difficulty: 3,
    trending: true,
    popularity: 9,
    description: 'Runtime JavaScript para servidor',
    keywords: ['nodejs', 'node', 'v8', 'server', 'backend', 'npm', 'express']
  },
  'python': {
    name: 'python',
    displayName: 'Python',
    color: '#3776AB',
    bgColor: 'bg-blue-500',
    textColor: 'text-blue-100',
    gradient: 'from-blue-500 to-yellow-400',
    icon: SiPython,
    category: 'backend',
    difficulty: 2,
    trending: true,
    popularity: 10,
    description: 'Linguagem versátil e legível',
    keywords: ['python', 'py', 'django', 'flask', 'fastapi', 'data science', 'ml', 'ai']
  },
  'java': {
    name: 'java',
    displayName: 'Java',
    color: '#ED8B00',
    bgColor: 'bg-orange-600',
    textColor: 'text-orange-100',
    gradient: 'from-orange-600 to-red-600',
    icon: FaJava,
    category: 'backend',
    difficulty: 4,
    trending: false,
    popularity: 8,
    description: 'Linguagem orientada a objetos enterprise',
    keywords: ['java', 'jvm', 'spring', 'hibernate', 'enterprise', 'oracle']
  },
  'docker': {
    name: 'docker',
    displayName: 'Docker',
    color: '#2496ED',
    bgColor: 'bg-blue-500',
    textColor: 'text-blue-100',
    gradient: 'from-blue-500 to-cyan-500',
    icon: SiDocker,
    category: 'devops',
    difficulty: 3,
    trending: true,
    popularity: 9,
    description: 'Plataforma de containerização',
    keywords: ['docker', 'container', 'virtualization', 'devops', 'microservices']
  },
  'html': {
    name: 'html',
    displayName: 'HTML5',
    color: '#E34F26',
    bgColor: 'bg-orange-500',
    textColor: 'text-orange-100',
    gradient: 'from-orange-500 to-orange-600',
    icon: SiHtml5,
    category: 'frontend',
    difficulty: 1,
    trending: false,
    popularity: 10,
    description: 'Linguagem de marcação para web',
    keywords: ['html', 'html5', 'markup', 'web', 'semantic', 'structure']
  },
  'css': {
    name: 'css',
    displayName: 'CSS3',
    color: '#1572B6',
    bgColor: 'bg-blue-600',
    textColor: 'text-blue-100',
    gradient: 'from-blue-600 to-blue-700',
    icon: SiCss3,
    category: 'frontend',
    difficulty: 2,
    trending: false,
    popularity: 10,
    description: 'Linguagem de estilos para web',
    keywords: ['css', 'css3', 'styles', 'web', 'responsive', 'animation']
  },
  'default': {
    name: 'default',
    displayName: 'Projeto',
    color: '#6B7280',
    bgColor: 'bg-slate-500',
    textColor: 'text-slate-100',
    gradient: 'from-slate-500 to-slate-600',
    icon: FaCode,
    category: 'other',
    difficulty: 1,
    trending: false,
    popularity: 1,
    description: 'Projeto de tecnologia',
    keywords: ['projeto', 'development', 'code', 'technology']
  }
};
